#!/bin/bash
mkdir -p deb/usr/bin/
mkdir -p target/

go build -o deb/usr/bin/gomuks

go get -u github.com/tulir/tcell
mkdir -p deb/usr/share/tcell/
rm -rf deb/usr/share/tcell/database
cp -r $GOPATH/src/github.com/tulir/tcell/terminfo/database deb/usr/share/tcell

version=$(cat deb/DEBIAN/control | grep Version | awk '{ print $2 }')
dpkg-deb --build deb target/gomuks-$version.deb
